name: artifact workflow
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm ci
            - name: Build artifact
              run: npm run build
            - name: List current directory
              run: ls -la
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: dist/
            - name: List current directory after upload
              run: ls -la
