name: artifact workflow
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: build artifact
              run: npm run build
            - name: list current directory
              run: ls -la
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: dist/
            - name: list current directory after upload
              run: ls -la
